# Generated by Django 5.1.7 on 2025-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_basket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'waiting'), (2, 'paid'), (3, 'sent'), (4, 'delivered'), (5, 'canceled')], default='waiting', max_length=250),
        ),
    ]
