# Generated by Django 5.1.7 on 2025-03-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_profile_remove_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='total_price',
        ),
    ]
